name: Build and Deploy Backend

on:
  push:
    branches: [devops-test] # or your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=build-${{ github.run_number }}
          docker build -t gautamabhis/edutrust-backend:$IMAGE_TAG .
          docker push gautamabhis/edutrust-backend:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: gautamabhis/edutrust-backend:${{ env.IMAGE_TAG }}
          format: 'table'

      - name: Checkout chart repo
        uses: actions/checkout@v3
        with:
          repository:gautamabhish/edutrustDevops
          token: ${{ secrets.CICDTOKEN }} # needs write access
          path: chart-repo
          ref: main # or your chart branch
      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y yq   # Install yq for YAML processing

      - name: Update values.yaml
        run: |
          cd chart-repo/
          yq e ".image.tag = \"$IMAGE_TAG\"" -i helm/edutrust-chart/values.yaml

      - name: Commit and push chart update
        run: |
          cd chart-repo
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update image tag to $IMAGE_TAG"
          git push
